sudo: false
language: java
dist: xenial

jdk:
  - openjdk8

# See https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338
addons:
  apt:
    packages:
      - oracle-java8-installer
